### ISSUE TITLE
modify templates to include new metadata from images

### ISSUE THREAD

**Issue by admiralstrand** [notionparallax/compo#9]

**Comment by notionparallax** [comment]
![image](https://cloud.githubusercontent.com/assets/1865196/14268235/8e9ad622-fa8d-11e5-8988-9b9ee4edad66.png)

Is there ever a time where the `title` (whale fish) would be different to the `artwork_name` ? Or would it always be some composition of the `artist_name`, `artwork_date`, `artwork_name` ?

we can keep them as different things, or we con combine them.

@admiralstrand what do you think?

**Comment by admiralstrand** [comment]
artist_name, artwork_date, artwork_name  always
